{
 "title": "Basement electricity usage",
 "time": { "from": "2021-09-26T07:00:00.000Z", "to": "2021-10-01T06:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "location",
    "label": "location",
    "query": "SHOW TAG VALUES WITH KEY=device_name;"
   },
   { "name": "plan", "query": "SHOW TAG VALUES WITH KEY=plan;" }
  ]
 },
 "panels": [
  {
   "title": "Total cost for the selected plans and time range",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Energy usage",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy_usage",
     "query": "SELECT mean(\"usage\")  / 1000 FROM \"energy_usage\" WHERE (\"device_name\" =~ /^$location$/) AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$location(-1,2,3)?$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rates",
     "query": "SELECT last(\"price\") FROM \"pge_rates\" WHERE (\"plan\" = 'EV2A' AND \"location\" = 'sfo') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "plan", "operator": "=~", "value": "/^$plan$/" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "PG&E" }
     ]
    }
   ]
  },
  {
   "title": "Plan pricing",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "alias": "Price per kWh (plan: $plan)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rates",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "provider", "operator": "=", "value": "PG&E" },
      { "condition": "AND", "key": "plan", "operator": "=~", "value": "/^$plan$/" }
     ]
    }
   ]
  },
  {
   "title": "Cumulative usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "alias": "Basement usage",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "energy_usage",
     "query": "SELECT cumulative_sum(mean(\"usage\")) FROM \"energy_usage\" WHERE (\"device_name\" = 'basement-1,2,3') AND $timeFilter GROUP BY time(1h) fill(previous)",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "cumulative_sum"
       }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$location(-1,2,3)?$/" }
     ]
    }
   ]
  },
  {
   "title": "Energy usage (via cloud)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "Basement usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy_usage",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$location(-1,2,3)?$/" }
     ]
    }
   ]
  },
  {
   "title": "days worth of data with 1s resolution",
   "type": "stat",
   "description": "This should be equal to the selected time range. If it's smaller, that means we are omitting data. Try selected a smaller range",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "days worth of data with second resolution",
     "measurement": "energy_usage",
     "query": "SELECT mean(\"usage\")  / 1000 FROM \"energy_usage\" WHERE (\"device_name\" =~ /^$location$/) AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ " / 86400" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$location(-1,2,3)?$/" }
     ]
    }
   ]
  },
  {
   "title": "Hourly energy cost",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 17, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "alias": "Energy usage",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "energy_usage",
     "query": "SELECT mean(\"usage\")  / 1000 FROM \"energy_usage\" WHERE (\"device_name\" =~ /^$location$/) AND $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device_name", "operator": "=~", "value": "/^$location(-1,2,3)?$/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "rates",
     "query": "SELECT last(\"price\") FROM \"pge_rates\" WHERE (\"plan\" = 'EV2A' AND \"location\" = 'sfo') AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "price" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ],
     "tags": [
      { "key": "plan", "operator": "=~", "value": "/^$plan$/" },
      { "condition": "AND", "key": "provider", "operator": "=", "value": "PG&E" }
     ]
    }
   ]
  }
 ]
}